### ISSUE TITLE
Parsing Error Raised when Attempting to Run Example Code

### ISSUE THREAD

**Issue by Arahat-Chikkatur** [scaleapi/llm-engine#146] opened 2023-07-20 04:10 UTC
I installed the scale-llm engine using pip for windows and am currently running it on python. To test the engine, I ran the example code shown on the website for the engine. However, I ran into the following error. 
![image](https://github.com/scaleapi/llm-engine/assets/140039540/c35e2950-95a9-4919-aabf-2b4e9975daef)
Below is the code that was used, along with the code that raised the error
![image](https://github.com/scaleapi/llm-engine/assets/140039540/7e6a68c8-0c7c-4f8e-a891-a1a6a49c7080)
![image](https://github.com/scaleapi/llm-engine/assets/140039540/7afde3e6-c11b-4660-b5ce-803820354e19)
Any help would be appreciated

**Comment by rkaplan** [comment] 2023-07-20 04:31
Thanks for filing @Arahat-Chikkatur. Looking into it.

**Comment by Arahat-Chikkatur** [comment] 2023-07-20 05:01
I have fixed the Not Found Error using the following fix
![image](https://github.com/scaleapi/llm-engine/assets/140039540/78794743-92e6-4c44-9e51-02feed009f23)
As os.path.join added a backslash instead of forward slash. However, I now get an error for an invalid API key despite using a valid key.  Running this code on a mac with the same key worked, meaning it is not an issue with the key. Any help would be apprieciated.

**Comment by yunfeng-scale** [comment] 2023-07-21 03:12
Hi @Arahat-Chikkatur, thanks for reporting issues on Windows. However we're focused on supporting macOS / Linux right now and we don't have resource to support running LLM Engine e2e on Windows at this time.

**Comment by yixu34** [comment] 2023-07-21 20:14
We can leave this issue open for another 30 days or so in case there is additional demand/interest in Windows, but yeah what @yunfeng-scale said is correct.

**Comment by saiatmakuri** [comment] 2023-08-31 00:31
With #225, the Completions API should work on Windows machines and I'm unable to reproduce this issue. 

I believe the underlying issue lied with how the auth was done with the request at the time of this PR. Specifically, missing this param in the POST request:
```
auth=(api_key, "")
```

This was addressed in https://github.com/scaleapi/llm-engine/pull/181.

**Closed by saiatmakuri** 2023-08-31 00:31 UTC
